controller_list:
  - name: arm_robot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
